[platformio]
default_envs = esp32s3_watch
src_dir = main
include_dir = include

[env:esp32s3_watch]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.flash_size = 16MB
board_build.partitions = partitions.csv

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -D CORE_DEBUG_LEVEL=3
    -D VEYRO_FW_VERSION="5.0.0"
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=1

lib_deps =
    lvgl/lvgl@^8.3.11
