; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Board options: data rate, built-in LED, reset method

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    sparkfun/MAX30105 Library@^1.1.1
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.7
    hieromonik/ESP32 BLE Arduino@^1.0.1

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1

upload_speed = 921600
